apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  nginx.conf: |
    events { worker_connections 1024; }
    http {
        # Log Format พิเศษ: จะบอกว่าส่งไปหา Upstream (VM) ตัวไหน
        log_format proxy_log '$remote_addr - $remote_user [$time_local] '
                            '"$request" $status $body_bytes_sent '
                            '"$http_referer" "$http_user_agent" '
                            'proxy_to: $upstream_addr';

        upstream gitops_backend {
            {{- range .Values.backend.nodes }}
            server {{ . }}:{{ $.Values.backend.port }};
            {{- end }}
        }

        server {
            listen 80;
            
            # เก็บ Log ลงไฟล์ที่เราจะ Mount ออกไปที่ HostPath
            access_log /var/log/nginx/access.log proxy_log;
            error_log /var/log/nginx/error.log warn;

            location / {
                proxy_pass http://gitops_backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }