replicaCount: 1

image:
  repository: 192.168.11.128:8082/docker-hosted/nginx
  tag: "1.25"
  pullPolicy: IfNotPresent

backend:
  port: 30080
  nodes:
    - 192.168.11.129
    - 192.168.11.130

service:
  type: NodePort
  port: 80
  nodePort: 32000

logging:
  hostPath: /var/log/nginx-lb