replicaCount: 1

image:
  repository: 192.168.11.128:8082/docker-hosted/gitops-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: backend.local
  path: /
  pathType: Prefix

resources: {}
