apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-backend
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: gitops-backend
  template:
    metadata:
      labels:
        app: gitops-backend
    spec:
      nodeSelector:
          node-role.kubernetes.io/worker: worker
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 30000
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 30000
            initialDelaySeconds: 10
            periodSeconds: 5