apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitops-backend
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/service.serversscheme: http
    traefik.ingress.kubernetes.io/service.passhostheader: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: vm1
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitops-backend
                port:
                  number: 30000
