apiVersion: v1
kind: Service
metadata:
  name: gitops-backend
spec:
  type: ClusterIP
  selector:
    app: gitops-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080    
      nodePort: {{ .Values.service.nodePort }}  
